version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    driver: bridge

services:
  web-admin-app:
   image: devndl/ndl-apps:admin-web-app-1.0.2
   ports:
     - 8080:8080
   networks:
     - web-app-net

##End of Scripts