version: '3.7'

networks:
  web-app-net:
    name: my-web-app-net
    driver: bridge

volumes:
  barc-auth-data:

services:
  # barc-auth-app service
  barc-auth-app:
      #image: devndl/ndl-apps:auth-service-1.0
      image: auth-service:1.0
      build:
        context: .
        args:
          - APP_ENV=${APP_ENV}
      environment:
        - APP_ENV=${APP_ENV}
      ports:
        - 8080:8000
      depends_on:
        - barc-auth-db
        - redis
      networks:
          - web-app-net

  # barc-auth-mysql services
  barc-auth-db:
      image: mysql:8.0
      ports:
        - 3306:3306
      environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_ROOT_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      volumes:
        - barc-auth-data:/var/lib/mysql
      networks:
          - web-app-net

  # PhpMyAdmin service
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: barc-auth-db
        PMA_PORT: 3306
      ports:
        - 8081:80
      depends_on:
        - barc-auth-db
      networks:
          - web-app-net

  # Redis service
  redis:
      image: redis:alpine
      command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
      ports:
        - 6379:6379
      networks:
          - web-app-net

###End Of File
