version: "3.5"

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - 9200
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw              # Persistence data
    networks:
      - web-app-net
#    deploy:
#      replicas: 1
#      update_config:
#        parallelism: 1
#        delay: 5s
#      restart_policy:
#        condition: on-failure
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.elk-node-01 == yes

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - 25826
      - 5044
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    depends_on:
      - elasticsearch
    networks:
      - web-app-net
#    deploy:
#      replicas: 1
#      update_config:
#        parallelism: 1
#        delay: 5s
#      restart_policy:
#        condition: on-failure
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.elk-node-01 == yes

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - web-app-net
#    deploy:
#      replicas: 1
#      update_config:
#        parallelism: 1
#        delay: 5s
#      restart_policy:
#        condition: on-failure
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.elk-node-01 == yes

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file, e.g. commend was introduced for passing the file permission.
      - /var/lib/docker/containers:/var/lib/docker/containers:ro                    # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                                # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                                      # Allow access to log files and docker.sock
    depends_on:
      - logstash
    networks:
      - web-app-net
#    deploy:
#      replicas: 1
#      update_config:
#        parallelism: 1
#        delay: 5s
#      restart_policy:
#        condition: on-failure
#      placement:
#        constraints:
#          - node.role == worker
#          - node.labels.elk-node-01 == yes

##End of Scripts