# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first.rules"
# - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'prometheus'
#    # metrics_path defaults to '/metrics'
#    # scheme defaults to 'http'.
#    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['prom:9090']

#  - job_name: 'grafana'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['grafana:3000']

#  - job_name: "node"
#    scrape_interval: "15s"
#    static_configs:
#      - targets: ['exporter:9100']

  - job_name: 'api-gateway-app'
    scheme: https
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    #localhost || machine-ip || aws-public-dns:port
    static_configs:
      - targets: ['api-gateway-app']

  - job_name: 'authentication-app'
    metrics_path: '/api/auth/actuator/prometheus'
    scrape_interval: 5s
    #localhost || machine-ip || aws-public-dns:port
    static_configs:
      - targets: ['authentication-app:8080']

  - job_name: 'authorization-app'
    metrics_path: '/api/access/actuator/prometheus'
    scrape_interval: 5s
    #localhost || machine-ip || aws-public-dns:port
    static_configs:
      - targets: ['authorization-app:8081']

  - job_name: 'notification-app'
    metrics_path: '/api/notify/actuator/prometheus'
    scrape_interval: 5s
    #localhost || machine-ip || aws-public-dns:port
    static_configs:
      - targets: ['notification-app:8082']

  - job_name: 'content-container-app'
    metrics_path: '/api/content/actuator/prometheus'
    scrape_interval: 5s
    #localhost || machine-ip || aws-public-dns:port
    static_configs:
      - targets: ['content-container-app:8083']

#End Of File